### ISSUE TITLE
Poster / Thumbnail Width & Height

### ISSUE THREAD

**Issue by yassineatik** [muxinc/next-video#108]
I am wondering if there's another way to set a thumbnail , or the Poster is the thumbnail?
If yes, then the postaer must take full width and height of the video.
Here's a screenshot, the burger image is the poster (Thumbnail) .
![image](https://github.com/muxinc/next-video/assets/77692478/a91f3ffa-02d3-4b6d-a1d4-8e8f4bf01490)

**Comment by luwes** [comment]
try adding a CSS var to the `style` prop of the video component like so:

`style={{ '--media-object-fit': 'cover' }}`

that will make the poster and video cover the whole surface of its container.
note that it's still recommended to provide a poster thumbnail with the same aspect-ratio as the video because otherwise there will be parts of the image cut off.

let me know if this works. cheers

**Comment by yassineatik** [comment]
That actually works, thank you for your fast reply

**Comment by heff** [comment]
Closing because solved. Maybe we need some docs on this use case?
