### ISSUE TITLE
Multiple video player resizes on first load

### ISSUE THREAD

**Issue by heff** [muxinc/next-video#53]
After a from-scratch create-next-app and next-video init, embedding a video in the default next.js app home page results in a player that resizes twice.

Adding a width and height to the Video component did not help.

![](https://image.mux.com/0273J01m2Jg6YHrOPzbMGPQfjzc7DmFbS7/animated.gif?width=540&start=0)

**Comment by luwes** [comment]
it's now possible to set a width or height on the Video component itself, or when the parent container has dimensions the Video component should expand to 100% width.

in the the default Next.js template if you replace the center image with our video component there will still be resizing like in the gif above because the parent doesn't have dimensions so the child's media content makes the video component resize.
first the poster image, (w/ preload=metadata) then first loaded video rendition (360p or so) and maybe 2nd loaded rendition (720p or so)
